### ISSUE TITLE
Tollbox for Asura

### ISSUE THREAD

**Issue by TristPW** [michengs/tera-guide#8]
Hi!
I use a set of tools https://drive.google.com/file/d/1BxJMejAzaqZIskKHU7mY_lpREA0DwWNv/view for the Asura client https://tera-online.ml / . After copying the files to TeraToolbox\mods\tera-guide\ unfortunately some guide don't work.
[tera-guide] ERROR: Unable to load a script for the guide "9783":
 TypeError: this.__context.load is not a function
    at Guide.load (H:\Tera\TERA\TeraToolbox\mods\tera-guide-core\lib\core\guide.js:92:19)
    at Zone.load (H:\Tera\TERA\TeraToolbox\mods\tera-guide-core\lib\core\zone.js:142:10)
    at event (H:\Tera\TERA\TeraToolbox\mods\tera-guide-core\lib\core\commands.js:105:18)
    at String.subCommandHandler (H:\Tera\TERA\TeraToolbox\mods\command\index.js:315:16)
    at CommandBase.exec (H:\Tera\TERA\TeraToolbox\mods\command\index.js:225:16)
    at Command.exec (H:\Tera\TERA\TeraToolbox\mods\command\index.js:403:26)
    at H:\Tera\TERA\TeraToolbox\mods\tera-guide-core\lib\core\gui.js:31:31
    at Array.forEach (<anonymous>)
    at Object.callback (H:\Tera\TERA\TeraToolbox\mods\tera-guide-core\lib\core\gui.js:29:30)
    at Dispatch.handle (H:\Tera\TERA\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:414:45)

How can this be fixed?

**Comment by justkeepquiet** [comment]
You need use this version https://github.com/hsdn/tera-guide compatible with Asura.

**Comment by justkeepquiet** [comment]
Toolbox for Asura/Menma here: https://github.com/tera-private-toolbox/tera-toolbox

**Comment by TristPW** [comment]
Yes, I also tried to install guides there. The attempt was unsuccessful. Perhaps there is a solution to how the current guides can be imported into the toolbox https://github.com/tera-private-toolbox/tera-toolbox?

**Comment by justkeepquiet** [comment]
No ways. This project is no longer maintained. Just use latest tera-private-toolbox and tera-guide.

**Comment by TristPW** [comment]
In https://github.com/hsdn/tera-guide there are no some guides that are here.
It's a pity that your work can no longer be used. You were very good at it.

**Comment by justkeepquiet** [comment]
You need DRC guide (9783)?
Try to put it into the **guide** folder, it should work (hsdn/tera-guide supports of old-guides format).

**Comment by justkeepquiet** [comment]
You have already created an issue https://github.com/hsdn/tera-guide/issues/78 to add this guide. Unfortunately now I have little time to continue development. But I promise you that this guide will be added soon.

**Comment by justkeepquiet** [comment]
I fixed the DRC guide **9783.js**, it should work. Try it:
```js
// DRC
// made by michengs

const SPAWN_CIRCLES = true;
const steptwo = 2 * Math.PI / 30; //20 flowers in total
const SPAWNING_FIRST_CIRCLE_FLOWERS = [];
const SPAWNING_THIRD_CIRCLE_FLOWERS = [];

for (let angle = -Math.PI; angle <= Math.PI; angle += steptwo) {
	if (!SPAWN_CIRCLES) continue;

	SPAWNING_FIRST_CIRCLE_FLOWERS.push({
		"type": "spawn",
		"id": 553,
		"sub_delay": 5000,
		"distance": 680,
		"offset": angle
	});

	SPAWNING_THIRD_CIRCLE_FLOWERS.push({
		"type": "spawn",
		"id": 553,
		"sub_delay": 6000,
		"distance": 225,
		"offset": angle
	});

}

const SPAWNING_right_FLOWERS = []; //303
const SPAWNING_left_FLOWERS = []; //306

for (let distance = 50; distance <= 250; distance += 50) {
	SPAWNING_right_FLOWERS.push({
		"type": "spawn",
		"id": 553,
		"sub_delay": 5000,
		"distance": distance,
		"offset": 1.57
	},
	{
		"type": "spawn",
		"id": 553,
		"sub_delay": 5000,
		"distance": distance,
		"offset": -1.57
	},

	{
		"type": "spawn",
		"sub_type": "build_object",
		"id": 1,
		"sub_delay": 5000,
		"distance": 250,
		"ownerName": "SAFE SPOT",
		"message": "SAFE",
		"offset": -1.39
	},
	{
		"type": "spawn",
		"sub_type": "item",
		"id": 98260,
		"sub_delay": 5000,
		"distance": 250,
		"offset": -1.39

	},

	{
		"type": "spawn",
		"sub_type": "build_object",
		"id": 1,
		"sub_delay": 5000,
		"distance": 250,
		"ownerName": "SAFE SPOT",
		"message": "SAFE",
		"offset": 1.745
	},
	{
		"type": "spawn",
		"sub_type": "item",
		"id": 98260,
		"sub_delay": 5000,
		"distance": 250,
		"offset": 1.745

	});

	SPAWNING_left_FLOWERS.push({
		"type": "spawn",
		"id": 553,
		"sub_delay": 5000,
		"distance": distance,
		"offset": 1.57
	},
	{
		"type": "spawn",
		"id": 553,
		"sub_delay": 5000,
		"distance": distance,
		"offset": -1.57
	},
	{
		"type": "spawn",
		"sub_type": "build_object",
		"id": 1,
		"sub_delay": 5000,
		"distance": 250,
		"ownerName": "SAFE SPOT",
		"message": "SAFE",
		"offset": 1.39
	},
	{
		"type": "spawn",
		"sub_type": "item",
		"id": 98260,
		"sub_delay": 5000,
		"distance": 250,
		"offset": 1.39
	},
	{
		"type": "spawn",
		"sub_type": "build_object",
		"id": 1,
		"sub_delay": 5000,
		"distance": 250,
		"ownerName": "SAFE SPOT",
		"message": "SAFE",
		"offset": -1.745
	},
	{
		"type": "spawn",
		"sub_type": "item",
		"id": 98260,
		"sub_delay": 5000,
		"distance": 250,
		"offset": -1.745
	});
}

module.exports = {
	load(dispatch) {
		//
	},

	"s-783-1000-108-0": [{ "type": "text", "sub_type": "message", "message": "back stun", "message_TW": "后跳眩晕" }],
	"s-783-1000-109-0": [{ "type": "text", "sub_type": "message", "message": "Knockback", "message_TW": "后扫击退" }],
	"s-783-1000-119-0": [{ "type": "text", "sub_type": "message", "message": "energy", "message_TW": "蓄力捶地" }],
	"s-783-1000-127-0": [{ "type": "text", "sub_type": "message", "message": "thunder", "message_TW": "雷电!!" }],
	"dm-0-0-9783103": [{ "type": "text", "sub_type": "message", "message": "100", "message_TW": "100能量鉴定!!" }],
	//二王
	"s-783-2000-110-0": [{ "type": "text", "class_position": "tank", "sub_type": "message", "message": "front", "message_TW": "前砸闪避" }],
	"s-783-2000-111-0": [{ "type": "text", "class_position": "dps", "sub_type": "message", "message": "right back", "message_TW": "右后踢击退" },
		{ "type": "text", "class_position": "heal", "sub_type": "message", "message": "right back", "message_TW": "右后踢击退" }],
	"s-783-2000-115-0": [{ "type": "text", "class_position": "dps", "sub_type": "message", "message": "left back", "message_TW": "左后踢击退" },
		{ "type": "text", "class_position": "heal", "sub_type": "message", "message": "left back", "message_TW": "左后踢击退" }],
	"s-783-2000-119-0": [{ "type": "text", "sub_type": "message", "message": "jump stun", "message_TW": "跳跃眩晕" }],
	"s-783-2000-120-0": [{ "type": "text", "sub_type": "message", "message": "front + back", "message_TW": "前拳+后踢击退" }],
	"s-783-2000-316-0": [{ "type": "text", "sub_type": "message", "message": "Flame Blast", "message_TW": "火焰爆炸" }],
	"s-783-2000-317-0": [{ "type": "text", "sub_type": "message", "message": "water wave", "message_TW": "水波击飞" }],
	"s-783-2000-318-0": [{ "type": "text", "sub_type": "message", "message": "stun", "message_TW": "地毯眩晕" }].concat(SPAWNING_FIRST_CIRCLE_FLOWERS),

	//三王
	"s-783-3000-106-0": [{ "type": "text", "class_position": "tank", "sub_type": "message", "message": "front", "message_TW": "前推击退" }],
	"s-783-3000-109-0": [{ "type": "text", "class_position": "tank", "sub_type": "message", "message": "stun", "message_TW": "前插眩晕" }],
	"s-783-3000-112-0": [{ "type": "text", "class_position": "dps", "sub_type": "message", "message": "Knockback", "message_TW": "后扫击退" },
		{ "type": "text", "class_position": "heal", "sub_type": "message", "message": "Knockback", "message_TW": "后扫击退" }],
	"s-783-3000-301-0": [{ "type": "text", "sub_type": "message", "message": "diaup", "message_TW": "地刺击飞" }],

	"s-783-3000-303-0": [{ "type": "text", "sub_type": "message", "message": "right", "message_TW": "右" }].concat(SPAWNING_right_FLOWERS),
	"s-783-3000-306-0": [{ "type": "text", "sub_type": "message", "message": "left", "message_TW": "左" }].concat(SPAWNING_left_FLOWERS),
	"s-783-3000-309-0": [{ "type": "text", "sub_type": "message", "message": "Debuffs", "message_TW": "注视!!" }],
	"s-783-3000-315-0": [{ "type": "text", "sub_type": "message", "message": "suck blood", "message_TW": "恐惧吸血" }]
};
```

**Comment by TristPW** [comment]
This code works except for three errors.

[tera-guide] ERROR: Key "load" has invalid type.
[tera-guide] ERROR: Limit of records for key "s-783-2000-318-0" exceeded.
[tera-guide] ERROR: Limit of records for key "s-783-3000-303-0" exceeded.
[tera-guide] ERROR: Limit of records for key "s-783-3000-306-0" exceeded.

It looks like the error appears when using concat().
